Slumlords\Bundle\Entity\Bank:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        accountID:
            type: integer
        balance:
            type: float
    lifecycleCallbacks: {  }
