Slumlords\Bundle\Entity\Course:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        columns:
            type: integer
        name:
            type: string
            length: 100
        rows:
            type: integer
        active:
            type: boolean
    manyToMany:
        users:
            targetEntity: User
            mappedBy: courses
