Slumlords\Bundle\Entity\Log:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        logType:
            type: string
        timestamp:
            type: datetime
        amount:
            type: decimal
            nullable: true
        targetID:
            type: integer
            nullable: true
        originID:
            type: integer
            nullable: true
        propertyID:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
