Slumlords\Bundle\Entity\Property:
    type: entity
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        rent: 
            type: float
    lifecycleCallbacks: {  }

