Slumlords\Bundle\Entity\Property:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        accountID:
            type: integer
        rent: 
            type: float
    lifecycleCallbacks: {  }
    manyToOne:
        user:
            targetEntity: User
            inversedBy: property
            joinColumn:
                name: user_id
                referencedColumnName: id
    manyToOne:
        course:
            targetEntity: Course
            inversedBy: property
            joinColumn:
                name: course_id
                referencedColumnName: id
