Slumlords\Bundle\Entity\Property:
    type: entity
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        price:
            type: float
        rent: 
            type: float
        isActive:
            type: boolean
    lifecycleCallbacks: {  }
    manyToOne:
        owner:
            targetEntity: User
            joinColumn:
                name: owner_id
                referencedColumnName: id
        renter:
            targetEntity: User
            joinColumn:
                name: renter_id
                referencedColumnName: id
        course:
            targetEntity: Course
            joinColumn: 
                name: course_id
                referencedColumnName: id 
