Slumlords\Bundle\Entity\User:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        firstName:
            type: string
        lastName:
            type: string
        wage:
            type: decimal
    lifecycleCallbacks: {  }
    manyToMany:
        courses:
            targetEntity: Course 
            mappedBy: users
    oneToMany:
        property:
            targetEntity: Property
            mappedBy: users
