Slumlords\Bundle\Entity\User:
    type: entity
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        firstName:
            type: string
        lastName:
            type: string
        wage:
            type: decimal
    manyToMany:
        courses:
            targetEntity: Course
            inversedBy: users
            joinTable:
                name: users_courses
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    course_id: 
                        referencedColumnName: id
        groups:
            targetEntity: UserGroup
            joinColumn:
                name: group_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
