slumlords_homepage:
    pattern:  /
    defaults: { _controller: SlumlordsBundle:Default:index }

slumlords_desks:
    pattern: /desks
    defaults: { _controller: SlumlordsBundle:Default:desks }

slumlords_bank:
    pattern: /bank
    defaults: { _controller: SlumlordsBundle:Default:bank }