slumlords_homepage:
    pattern:  /
    defaults: { _controller: SlumlordsBundle:Default:index }

slumlords_admin:
    pattern:  /admin
    defaults: { _controller: SlumlordsBundle:Admin:index }

slumlords_admin_users:
    pattern:  /admin/users
    defaults: { _controller: SlumlordsBundle:Admin:users }

slumlords_admin_user_add:
    pattern:  /admin/users/add
    defaults: { _controller: SlumlordsBundle:Admin:userAdd }

slumlords_admin_user_edit:
    pattern:  /admin/users/{id}/edit
    defaults: { _controller: SlumlordsBundle:Admin:userEdit }

slumlords_admin_user_show:
    pattern:  /admin/users/{id}
    defaults: { _controller: SlumlordsBundle:Admin:userShow }

slumlords_admin_courses:
    pattern:  /admin/courses
    defaults: { _controller: SlumlordsBundle:Admin:courses }

slumlords_admin_course_add:
    pattern:  /admin/courses/add
    defaults: { _controller: SlumlordsBundle:Admin:courseAdd }

slumlords_admin_course_edit:
    pattern:  /admin/courses/{id}/edit
    defaults: { _controller: SlumlordsBundle:Admin:courseEdit }

slumlords_admin_course_show:
    pattern:  /admin/courses/{id}
    defaults: { _controller: SlumlordsBundle:Admin:courseShow }

slumlords_properties:
    pattern: /properties
    defaults: { _controller: SlumlordsBundle:Default:properties }

slumlords_properties_show:
    pattern: /properties/{id}
    defaults: { _controller: SlumlordsBundle:Default:propertiesShow }

slumlords_property_edit:
    pattern: /properties/{courseId}/{id}/edit
    defaults: { _controller: SlumlordsBundle:Default:propertyEdit }

slumlords_property_rent:
    pattern: /properties/{courseId}/{id}/rent
    defaults: { _controller: SlumlordsBundle:Default:propertyRent }

slumlords_property_offer:
    pattern: /properties/{courseId}/{id}/offer
    defaults: { _controller: SlumlordsBundle:Default:propertyOffer }

slumlords_property_offer_response:
    pattern: /properties/{courseId}/{id}/offer/response
    defaults: { _controller: SlumlordsBundle:Default:propertyOfferResponse }

slumlords_bank:
    pattern: /bank
    defaults: { _controller: SlumlordsBundle:Default:bank }

slumlords_user_attendance:
    pattern: /account/attendance/ 
    defaults: { _controller: SlumlordsBundle:Account:userAttendance }

slumlords_attendance:
    pattern: /properties/{courseId}/attendance
    defaults: { _controller: SlumlordsBundle:Default:attendance }

slumlords_attendance_property:
    pattern: /properties/{courseId}/attendance/{username}
    defaults: { _controller: SlumlordsBundle:Default:attendanceProperty }

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
